services:
    app:
        container_name: main-aztroz-game-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:8080"
        tty: true